name: "aws-sagemaker-pipeline: ci"

on:
  push:
    branches: ["main"]
    paths:
      - "aws-sagemaker-pipeline/**"
      - ".github/workflows/aws-sagemaker-pipeline-ci.yml"
  pull_request:
    paths:
      - "aws-sagemaker-pipeline/**"
      - ".github/workflows/aws-sagemaker-pipeline-ci.yml"

defaults:
  run:
    working-directory: aws-sagemaker-pipeline

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install
        run: make install
      - name: Lint
        run: make lint
      - name: Test
        run: make test

